/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://o4bz3ui4fbe6hj5gn5f27abcya.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_oeOkCdNSs",
        "userPoolWebClientId": "1s6p4f9mj68smjknaj2di3bosv",
        "identityPoolId": "us-east-1:7de6b050-1591-4d70-8e7d-c5a4647ae0c0"
    },
    "Storage": {
        "AWSS3": {
            "bucket": "filestoragestack-s3bucket64cb25af-1d87vn3jgujco",
            "region": "us-east-1"
        }
    }
};


export default awsmobile;
